package orm;

import java.sql.*;
import java.util.*;
import java.util.logging.*;

import logic.CohortData;
import sessionControl.Session;

public class SubAssessment extends BaseSubAssessment {
    /**
     * Constructor to create an object to retrieve and store a sub assessment found in the database.
     * 
     * Contains all information about this sub assessment. Non-specific to students.
     * 
     * @param subAssessmentID the subassessment ID
     * @param assessment the parent assessment
     */
    public SubAssessment(int subAssessmentID, Assessment assessment) {
        super(subAssessmentID, assessment);
    }

    /**
     * Constructor to create an object to retrieve and store a sub assessment found in the database related to a specific student.
     * 
     * @param subAssessmentID subassessment ID
     * @param studentID student's ID
     * @param assessment parent of the subassessment
     */
    public SubAssessment(int subAssessmentID, int studentID, Assessment assessment) {
        super(subAssessmentID, studentID, assessment);
    }
    
    /**
     * Constructor to create an object to retrieve and store a sub assessment found in the database.
     * 
     * Runs when creating a subAssessment for CohortData.subassessments - single 'master' subassessment object for each subassessment ID,
     * containing all related marks for that subassessment. Does not have a parent assessment.
     * 
     * @param subAssessmentID the ID of the subassessment
     */
    public SubAssessment(int subAssessmentID){
    	super(subAssessmentID);
    }
    
    /**
     * Constructor that creates a new object with the given data and insert it into the database.
     * 
     * The sub assessment ID will be auto-generated by the database.
     * 
     * @param name the name of the sub assessment
     * @param parentAssessment the Assessment object this sub assessment belongs to
     * @param assessmentPercent the percentage this sub assessment takes up in the parent assessment
     * @throws SQLException when there's an error with the SQL statement
     */
    public SubAssessment(String name, Assessment parentAssessment, int assessmentPercent) throws SQLException {
        super(name, parentAssessment, assessmentPercent);
    }

    /**
     * Method to get all the sub assessments in the database.
     * 
     * @return a List of SubAssessment objects
     */
    public static List<SubAssessment> getAllSubAssessments() {
        List<SubAssessment> allSubAssessments = new ArrayList<>();
        
        try {
            Statement s = Session.dbConn.getConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet subAssessmentRS = s.executeQuery("SELECT SubAssessmentID FROM SubAssessment");
            
            while (subAssessmentRS.next()) {
                allSubAssessments.add(new SubAssessment(subAssessmentRS.getInt("SubAssessmentID")));
            }
        } catch (java.lang.NullPointerException | SQLException ex) {
            Logger.getLogger(BaseStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return allSubAssessments;
    }
    
    /**
     * Update a single row of the SubAssessment table 
     * 	- called when the save changes button is hit.
     *  - SubAssessmentID number is omitted so that it can never be changed. 
     * @throws SQLException 
     */
    public void updateRow() throws SQLException {
    	String sql = "UPDATE SubAssessment SET SubAssessmentName = '"+this.getName().toString()+"', AssessmentID = "+this.getParentAssessment().getAssessmentID()+", AssessmentPercent = "+this.getAssessmentPercent()+", MaxMarks = "+this.getMaxMark()+" WHERE SubAssessmentID = " + this.getSubAssessmentID();
    	Statement stmt = Session.dbConn.getConnection().createStatement();
    	stmt.execute(sql);
    	stmt.close();
    }
    
    /**
     * Delete this student //TODO test
     * @throws SQLException
     */
    public void deleteRow() throws SQLException {
    	CohortData.subassessments.remove(this);
    	String sql = "DELETE from SubAssessment WHERE SubAssessmentID = " + this.getSubAssessmentID();
    	Statement stmt = Session.dbConn.getConnection().createStatement();
    	stmt.execute(sql);
    	stmt.close();
    }
}
